---
reads:
  User:
    - id: user

    - id: author
      count: reads_got

  Post:
    - id: post

  UserWeekly:
    - id:
        - author
        - week
        - year

  LeagueWeekly:
    - id:
        - league
        - locale
        - week
        - year
      count: post_{post}

  LeagueMonthly:
    - id:
        - league
        - locale
        - month
        - year
      count: post_{post}

  TeamWeekly:
    - id:
        - team
        - locale
        - week
        - year
      count: post_{post}

  TeamMonthly:
    - id:
        - team
        - locale
        - month
        - year
      count: post_{post}

  LeagueWeeklyLeaderboard:
    - id: 
        - league
        - week
        - year
      count: user_{author}

  LeagueMonthlyLeaderboard:
    - id: 
        - league
        - month
        - year
      count: user_{author}

  TeamWeeklyLeaderboard:
    - id: 
        - team
        - week
        - year
      count: user_{author}

  TeamMonthlyLeaderboard:
    - id: 
        - team
        - month
        - year
      count: user_{author}

  UserWeeklyDemographics:
    - id:
        - author
        - week
        - year
      count: {country}

comments:
  User:
    - id: user

    - id: author
      count: comments_got

  Post:
    - id: post

  UserWeekly:
    - id:
        - author
        - week
        - year

shares:
  User:
    - id: user

    - id: author
      count: shares_got

  Post:
    - id: post

  UserWeekly:
    - id:
        - author
        - week
        - year

tweets:
  User:
    - id: user

    - id: author
      count: tweets_got

  Post:
    - id: post

  UserWeekly:
    - id:
        - author
        - week
        - year

likes:
  User:
    - id: user

    - id: author
      count: likes_got

  Post:
    - id: post

  UserWeekly:
    - id:
        - author
        - week
        - year

gplus:
  User:
    - id: user

    - id: author
      count: gplus_got

  Post:
    - id: post

  UserWeekly:
    - id:
        - author
        - week
        - year

logins: 
  User:
    - id: user


follow:
  User:
    - id: user

    - id: user
      count: follow_actions_total

    - id: other_user
      count: followers

    - id: other_user
      count: followers_actions_total

unfollow:
  User:
    - id: user
      count: follow
      change: -1

    - id: other_user
      count: followers
      change: -1

votes_mwp:
  User:
    - id: user


post_create:
  User:
    - id: user

  UserWeekly:
    - id:
        - user
        - week
        - year


feature:
  User:
    - id: user
      count: feature_{channel}


reactions:
  User:
    - id: user

    - id: author
      count: reactions_got

  Post:
    - id: post
